# permissions for end users to view nginx2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx2-viewer-role
rules:
- apiGroups:
  - demo.example.com
  resources:
  - nginx2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.example.com
  resources:
  - nginx2s/status
  verbs:
  - get
