# permissions for end users to edit nginx2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx2-editor-role
rules:
- apiGroups:
  - demo.example.com
  resources:
  - nginx2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.example.com
  resources:
  - nginx2s/status
  verbs:
  - get
